name: 'Setup Python environment'
description: 'Setup a Python environment and add it to the PATH, additionally providing proxy support'
author: 'GitHub'
inputs:
  python-version:
    description: 'Version range or exact version of a Python version to use, using semvers version range syntax.'
    default: '3.x'
  architecture:
    description: 'The target architecture (x86, x64) of the Python interpreter.'
    default: 'x64'
# Deprecated option, do not use. Will not be supported after October 1, 2019
  version:
    description: 'Deprecated. Use python-version instead. Will not be supported after October 1, 2019'
    deprecationMessage: 'The version property will not be supported after October 1, 2019. Use python-version instead'
runs:
  using: 'node12'
  main: 'lib/setup-python.js'

steps:
- uses: actions/checkout@master
- uses: actions/setup-python@v1
  with:
    python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
    architecture: 'x64' # (x64 or x86)
- run: python my_script.py
